unique_ids:
  assets:
    standard-page.html: 6PKRQ6NMK2NDVHDHSKPHKWGE7E7DHY52
    theme.css: 66NPNCNNUV623SP645FU6SRQPRGMNQMH
  forms:
    collectPayment: '1736795449575987147272917.5334'
    landingPage: ADQ6KDRGH7Y2J5FZD4APXWPKCHOA2PGY
    sendInvoice: '1736795467958879845247810.6202'
  modules: {}
  scripts: {}
  server_modules: {}
