unique_ids:
  assets:
    standard-page.html: 6PKRQ6NMK2NDVHDHSKPHKWGE7E7DHY52
    theme.css: 66NPNCNNUV623SP645FU6SRQPRGMNQMH
  forms:
    Form1: ADQ6KDRGH7Y2J5FZD4APXWPKCHOA2PGY
  modules: {}
  scripts: {}
  server_modules: {}
